name    'dalen-preseed_package'
version '1.0.0'
source 'git://github.com/dalen/puppet-preseed_package'
author 'dalen'
license 'Apache 2.0'
summary 'Install package with preseed file'
description 'Allows defining a package and preseed file using a single resource.'
project_page 'https://github.com/dalen/puppet-preseed_package'
dependency 'puppetlabs/stdlib', '>= 2.3.1'
